### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by jvarghese01** [NYPL-discovery/bulk-export-reader#13]
After I do a docker run, I get the following error:

```
Error parsing event message. SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/src/_container.js:42:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

After I comment out the last line in the Docker file: CMD....

The programs runs and returns: "No event message passed."

**Comment by jvarghese01** [comment]
I don't think that may be a valid command.  Also don't you need to run npm install and setup/run the app in the container.  That all seems to be commented out in the Dockerfile.

**Comment by jvarghese01** [comment]
looks better Kris.  Now I just get the following error/response:

```

Loading bulk export reader
{ CredentialsError: Missing credentials in config
```

I think I just need some credentials in config as the error says.  I think we can close this issue.
